# see https://github.com/FAForever/fa/blob/3291ca4cdb6f3d0d2d8cba1abbe9b2c30c456213/lua/ui/notify/defaultmessages.lua  # noqa: E501
ACU_UPGRADE_NOTIFIERS = {
    "aeon": {
        "ARAS": ("eras_btn_up", "back"),
        "Advanced Gun Range Upgrade": ("ecba_btn_up", "lch"),
        "Advanced Resource Allocation": ("eras_btn_up", "back"),
        "Chrono Dampener": ("cd_btn_up", "back"),
        "Gun (Advanced Range)": ("ecba_btn_up", "lch"),
        "Gun (Range)": ("cba_btn_up", "lch"),
        "Gun (Speed)": ("hsa_btn_up", "rch"),
        "Gun Range Upgrade": ("cba_btn_up", "lch"),
        "Gun Speed Upgrade": ("hsa_btn_up", "rch"),
        "Heavy Shield": ("phtsg_btn_up", "back"),
        "RAS": ("ras_btn_up", "back"),
        "Resource Allocation": ("ras_btn_up", "back"),
        "Sensor Suite": ("ess_btn_up", "rch"),
        "Sensors": ("ess_btn_up", "rch"),
        "Shield": ("ptsg_btn_up", "back"),
        "Shield Heavy": ("phtsg_btn_up", "back"),
        "T2": ("aes_btn_up", "lch"),
        "T3": ("ees_btn_up", "lch"),
        "Tech 2": ("aes_btn_up", "lch"),
        "Tech 3": ("ees_btn_up", "lch"),
        "Teleporter": ("pqt_btn_up", "back"),
    },
    "cybran": {
        "Cloaking": ("cfs_btn_up", "back"),
        "Gun (Speed&Range)": ("acu_btn_up", "lch"),
        "Gun Upgrade": ("acu_btn_up", "lch"),
        "Laser": ("mlg_btn_up", "rch"),
        "Microwave Laser": ("mlg_btn_up", "rch"),
        "Nano Repair": ("srs_btn_up", "back"),
        "Nano-Repair": ("srs_btn_up", "back"),
        "RAS": ("ras_btn_up", "back"),
        "Resource Allocation": ("ras_btn_up", "back"),
        "Stealth": ("sfs_btn_up", "back"),
        "T2": ("aes_btn_up", "lch"),
        "T3": ("ees_btn_up", "lch"),
        "Tech 2": ("aes_btn_up", "lch"),
        "Tech 3": ("ees_btn_up", "lch"),
        "Teleporter": ("pqt_btn_up", "back"),
        "Torpedo": ("ntt_btn_up", "rch"),
    },
    "nomads": {
        "ARAS": ("", ""),  # doesn't exist??
        "Advanced Intel Probe": ("ip_btn_up", "rch"),
        "Advanced Resource Allocation": ("", ""),  # doesn't exit??
        "Capacitor": ("acap_btn_up", "back"),
        "Double Gun Upgrade": ("hamc2_btn_up", "rch"),
        "Gun (Speed&Range)": ("hamc_btn_up", "rch"),
        "Gun Upgrade": ("hamc_btn_up", "rch"),
        "Intel Probe": ("ip_btn_up", "rch"),
        "Locomotor": ("il_btn_up", "lch"),
        "Movement Speed Upgrade": ("il_btn_up", "lch"),
        "Orbital Bombardment": ("heo_btn_up", "back"),
        "Power Armor": ("sepa_btn_up", "back"),
        "RAS": ("ras_btn_up", "back"),
        "Rapid Repair": ("se_btn_up", "back"),
        "Resource Allocation": "ras_btn_up",
        "Second Gun": ("hamc2_btn_up", "rch"),
        "T2": ("aes_btn_up", "lch"),
        "T3": ("ees_btn_up", "lch"),
        "Tech 2": ("aes_btn_up", "lch"),
        "Tech 3": ("ees_btn_up", "lch"),
        "Teleporter": ("pqt_btn_up", "back"),  # doesn't exist??
    },
    "seraphim": {
        "ARAS": ("eras_btn_up", "rch"),
        "Advanced Nano Repair": ("adss_btn_up", "back"),
        "Advanced Nano-Repair": ("adss_btn_up", "back"),
        "Advanced Regen Aura": ("anrf_btn_up", "lch"),
        "Advanced Resource Allocation": ("eras_btn_up", "back"),
        "Big Gun Upgrade": ("cba_btn_up", "lch"),
        "Gun (Speed&Range)": ("hsa_btn_up", "rch"),
        "Gun (Splash)": ("cba_btn_up", "lch"),
        "Gun Upgrade": ("hsa_btn_up", "rch"),
        "Nano Repair": ("dss_btn_up", "back"),
        "Nano-Repair": ("dss_btn_up", "back"),
        "RAS": ("ras_btn_up", "rch"),
        "Rapid Restoration Field": ("anrf_btn_up", "lch"),
        "Regen Aura": ("nrf_btn_up", "lch"),
        "Resource Allocation": ("ras_btn_up", "rch"),
        "Restoration Field": ("nrf_btn_up", "lch"),
        "T2": ("aes_btn_up", "lch"),
        "T3": ("ees_btn_up", "lch"),
        "Tactical Missile": ("tml_btn_up", "back"),
        "Tech 2": ("aes_btn_up", "lch"),
        "Tech 3": ("ees_btn_up", "lch"),
        "Teleporter": ("pqt_btn_up", "back"),
    },
    "uef": {
        "Billy": ("srtn_btn_up", "back"),
        "Gun (Damage&Range)": ("hamc_btn_up", "rch"),
        "Gun Upgrade": ("hamc_btn_up", "rch"),
        "Left Drone": ("led_btn_up", "back"),
        "Nano Repair": ("dsu_btn_up", "lch"),
        "Nano-Repair": ("dsu_btn_up", "lch"),
        "RAS": ("ras_btn_up", "rch"),
        "Resource Allocation": ("ras_btn_up", "rch"),
        "Right Drone": ("red_btn_up", "back"),
        "Shield": ("psg_btn_up", "back"),
        "Shield Field": ("sgf_btn_up", "back"),
        "T2": ("aes_btn_up", "lch"),
        "T3": ("ees_btn_up", "lch"),
        "Tactical Missile": ("tm_btn_up", "back"),
        "Tactical Nuke": ("srtn_btn_up", "back"),
        "Tech 2": ("aes_btn_up", "lch"),
        "Tech 3": ("ees_btn_up", "lch"),
        "Teleporter": ("pqt_btn_up", "lch"),
    },
}

UNIT_NOTIFIERS = {
    "experimentals": {
        "Ahwassa": "xsa0402",
        "Atlantis": "ues0401",
        "Czar": "uaa0310",
        "Fatboy": "uel0401",
        "Galactic Colossus": "ual0401",
        "Mavor": "ueb2401",
        "Megalith": "xrl0403",
        "Monkeylord": "url0402",
        "Novax Satellite Station": "xeb2402",
        "Paragon": "xab1401",
        "Salvation": "xab2307",
        "Scathis": "url0401",
        "Soulripper": "ura0401",
        "Tempest": "uas0401",
        "Yolona Oss": "xsb2401",
        "Ythotha": "xsl0401",
    },
    "cybran": {
        "Tech 3 Artillery construction": "urb2302",
        "Tech 3 Static Artillery": "urb2302",
        "Nuke Silo construction": "urb2305",
        "Nuke Launcher": "urb2305",
        "Tech 2 Land HQ": "urb0201",
        "Tech 3 Land HQ": "urb0301",
        "Tech 2 Air HQ": "urb0202",
        "Tech 3 Air HQ": "urb0302",
        "Tech 2 Naval HQ": "urb0203",
        "Tech 3 Naval HQ": "urb0303",
    },
    "seraphim": {
        "Tech 3 Artillery construction": "xsb2302",
        "Tech 3 Static Artillery": "xsb2302",
        "Nuke Silo construction": "xsb2305",
        "Nuke Launcher": "xsb2305",
        "Tech 2 Land HQ": "xsb0201",
        "Tech 3 Land HQ": "xsb0301",
        "Tech 2 Air HQ": "xsb0202",
        "Tech 3 Air HQ": "xsb0302",
        "Tech 2 Naval HQ": "xsb0203",
        "Tech 3 Naval HQ": "xsb0303",
    },
    "aeon": {
        "Tech 3 Artillery construction": "uab2302",
        "Tech 3 Static Artillery": "uab2302",
        "Nuke Silo construction": "uab2305",
        "Nuke Launcher": "uab2305",
        "Tech 2 Land HQ": "uab0201",
        "Tech 3 Land HQ": "uab0301",
        "Tech 2 Air HQ": "uab0202",
        "Tech 3 Air HQ": "uab0302",
        "Tech 2 Naval HQ": "uab0203",
        "Tech 3 Naval HQ": "uab0303",
    },
    "uef": {
        "Tech 3 Artillery construction": "ueb2302",
        "Tech 3 Static Artillery": "ueb2302",
        "Nuke Silo construction": "ueb2305",
        "Nuke Launcher": "ueb2305",
        "Tech 2 Land HQ": "ueb0201",
        "Tech 3 Land HQ": "ueb0301",
        "Tech 2 Air HQ": "ueb0202",
        "Tech 3 Air HQ": "ueb0302",
        "Tech 2 Naval HQ": "ueb0203",
        "Tech 3 Naval HQ": "ueb0303",
    },
}

ACU_BLUEPRINTS = {
    "cybran": "url0001",
    "seraphim": "xsl0001",
    "aeon": "ual0001",
    "uef": "uel0001",
}
