; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; #define PowerShellExe "powershell.exe"
; #define PowerShellCommandParam "-ExecutionPolicy Bypass -Command"

; #define ExecPowerShell(str Command) \
;   Local[0] = PowerShellCommandParam + " " + AddQuotes(Command), \
;   Message("Executing PowerShell command: " + Local[0]), \
;   ExecAndGetFirstLine(PowerShellExe, Local[0])
;
; #define BUILD_VERSION ExecPowerShell("Write-Host $env:BUILD_VERSION")
#define FAF_EXE "FAForever.exe"
#define FAF_URL "https://faforever.com"

#ifndef BUILD_VERSION
#define BUILD_VERSION "0.0.0"
#endif

#ifndef WORKING_DIR
#define WORKING_DIR ""
#endif


[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{CD60B7C9-6E6F-4551-8D27-D09F8AC11B3C}
AppName=FAF Python Client
AppVersion={#BUILD_VERSION}
AppPublisher=FAForever
AppPublisherURL={#FAF_URL}
AppSupportURL={#FAF_URL}
AppUpdatesURL={#FAF_URL}
DefaultDirName={autopf}\FAF Python Client
UninstallDisplayIcon={app}\{#FAF_EXE}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=dist
OutputBaseFilename=FAF.Python.Client-{#BUILD_VERSION}
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#WORKING_DIR}\faf_python_client\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\FA Forever"; Filename: "{app}\{#FAF_EXE}"
Name: "{autodesktop}\FA Forever"; Filename: "{app}\{#FAF_EXE}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#FAF_EXE}"; Description: "{cm:LaunchProgram,FA Forever}"; Flags: nowait postinstall skipifsilent
