name: Checks

on:
  push:
  pull_request:
    branches: [ develop ]

jobs:
  checks:
    runs-on: windows-latest
    env:
      PYWHEEL_INFIX: "cp36"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.7
          architecture: x86

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sip==4.19.8
          pip install pyqt5==5.7.1
          pip install https://github.com/FAForever/python-wheels/releases/download/2.0.0/pywin32-221-${{ env.PYWHEEL_INFIX }}-${{ env.PYWHEEL_INFIX }}m-win32.whl
          pip install wheel
          pip install pytest
          pip install cx_Freeze==5.0.2
          pip install -r requirements.txt

      - name: Copy required dlls
        run: |
          xcopy ${{ env.pythonLocation }}\\lib\\site-packages\\pywin32_system32 .

      - name: Test with pytest
        run: |
          python runtests.py -vv --full-trace
